
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 12 16:37:37 ART 2025
//----------------------------------------------------

package AnalizadorLexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ParentesisCierra = 15;
  public static final int ParentesisAbre = 14;
  public static final int Suma = 10;
  public static final int Numero = 20;
  public static final int True = 7;
  public static final int LlaveCierra = 18;
  public static final int Identificador = 19;
  public static final int Int = 2;
  public static final int False = 8;
  public static final int PuntoYComa = 16;
  public static final int Main = 5;
  public static final int EOF = 0;
  public static final int LlaveAbre = 17;
  public static final int Division = 13;
  public static final int Resta = 11;
  public static final int Return = 6;
  public static final int error = 1;
  public static final int Bool = 3;
  public static final int Void = 4;
  public static final int Igual = 9;
  public static final int Multiplicacion = 12;
}

